# Python Basics with Numpy

In [24]:
test = "Hello World"

In [2]:
print('test:', test)

test: Hello World


## 1 - Building basic funtions with numpy
### 1.1 - sigmoid function, np.exp()

In [13]:
import math

def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

In [14]:
basic_sigmoid(3)

0.9525741268224334

In [15]:
x = [1,2,3]
basic_sigmoid(x)
# you will get an error because x is a vector

TypeError: bad operand type for unary -: 'list'

In [16]:
import numpy as np

x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [17]:
# example of vecotr operation
x = np.array([1,2,3])
print(x+3)

[4 5 6]


In [18]:
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [19]:
x = np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

### 1.2 - Sigmoid gradient

In [29]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = s(1 - s)
    
    return ds

In [30]:
x = np.array([1,2,3])
print('sigmoid_derivative(x) =', str(sigmoid_derivative(x)))

TypeError: 'numpy.ndarray' object is not callable

### 1.3 - Reshaping arrays ###

In [ ]:
# Graded Function: image2vector
def image2vector(image):
    v = (image.shape[0]*image.shape[1]*image.shape[2], 1)
    return v