In [1]:
import numpy as np

a = np.random.randn(5)
a

array([ 1.22262841,  0.43636885, -0.36248972,  0.47596071,  0.3765309 ])

In [2]:
a.shape
# Don't use this

(5,)

In [3]:
a.T

array([ 1.22262841,  0.43636885, -0.36248972,  0.47596071,  0.3765309 ])

In [4]:
np.dot(a, a.T)

2.184950918478894

In [7]:
a = np.random.rand(5, 1)
print(a)

[[0.76320203]
 [0.68275364]
 [0.89830034]
 [0.11728469]
 [0.6043202 ]]


In [8]:
print(a.T)

[[0.76320203 0.68275364 0.89830034 0.11728469 0.6043202 ]]
