In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.2195691   0.97374972  0.35650128  1.94454989 -0.27692045]


In [3]:
# it's neither row vector nor column vector
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.2195691   0.97374972  0.35650128  1.94454989 -0.27692045]


In [5]:
print(np.dot(a, a.T))

4.981451457468327


In [7]:
# do not use Rank 1 array
# so
a = np.random.randn(5, 1)
print(a)

[[ 0.79851897]
 [-0.73382895]
 [-1.92053975]
 [ 0.19373744]
 [ 0.47000771]]


In [8]:
print(a.T)

[[ 0.79851897 -0.73382895 -1.92053975  0.19373744  0.47000771]]


In [9]:
print(np.dot(a, a.T))

[[ 0.63763255 -0.58597634 -1.53358743  0.15470302  0.37531007]
 [-0.58597634  0.53850493  1.40934767 -0.14217014 -0.34490526]
 [-1.53358743  1.40934767  3.68847294 -0.37208046 -0.90266849]
 [ 0.15470302 -0.14217014 -0.37208046  0.0375342   0.09105809]
 [ 0.37531007 -0.34490526 -0.90266849  0.09105809  0.22090725]]


In [12]:
assert(a.shape == (5, 1))